Recruit.create!(name: "Zavier Maxen")
Recruit.create!(name: "Artur Armen")
Recruit.create!(name: "Alfredo Grosvenor")
Recruit.create!(name: "Julio Linwood")
Recruit.create!(name: "Albano Pacey")
Recruit.create!(name: "Ra Aneurin")